# when removing SC or PVC, the bucket resources will be cleared and deleted together.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-obs5
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: obs-sc5
