apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obs-default-ds
spec:
  selector:
    matchLabels:
      app: nginx-obs
  template:
    metadata:
      labels:
        app: nginx-obs
    spec:
      containers:
        - image: nginx
          name: nginx-obs
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date -u) >> /mnt/obs/outfile; sleep 5; done"]
          volumeMounts:
            - mountPath: /mnt/obs
              name: obs-data
      volumes:
        - name: obs-data
          persistentVolumeClaim:
            claimName: obs-default-pvc
