kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: obs-default-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: obs-default-sc
