kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-deny-resize-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  storageClassName: sfsturbo-deny-resize-sc
