apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sfsturbo-deny-resize-sc
provisioner: sfsturbo.csi.huaweicloud.com
allowVolumeExpansion: false
reclaimPolicy: Delete
parameters:
  shareType: STANDARD
