apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-allow-resize-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-allow-resize-sc
