apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obs-static-ds
spec:
  selector:
    matchLabels:
      app: obs-static
  template:
    metadata:
      labels:
        app: obs-static
    spec:
      containers:
        - image: nginx
          name: nginx-obs-custom
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date -u) >> /mnt/obs/outfile; sleep 5; done"]
          volumeMounts:
            - mountPath: /mnt/obs
              name: obs-data
      volumes:
        - name: obs-data
          persistentVolumeClaim:
            claimName: obs-static-pvc
