apiVersion: v1
kind: PersistentVolume
metadata:
  name: obs-static-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: obs.csi.huaweicloud.com
    volumeHandle: tf-xxx
