kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: obs-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: obs-static-pv
