apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-pvc-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-sc-snapshot
