apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-deny-expend-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-deny-resize-sc
