apiVersion: v1
kind: Pod
metadata:
  name: sfs-turbo-static-pod
spec:
  containers:
    - image: nginx
      name: nginx-sfsturbo-custom
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /mnt/sfsturbo/outfile; sleep 5; done"]
      volumeMounts:
        - mountPath: /mnt/sfsturbo
          name: sfsturbo-data
  volumes:
    - name: sfsturbo-data
      persistentVolumeClaim:
        claimName: sfs-turbo-static-pvc
