apiVersion: v1
kind: PersistentVolume
metadata:
  name: sfs-turbo-static-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: sfsturbo.csi.huaweicloud.com
    volumeHandle: 568ace6f-6368-46df-9665-1b542b1c0cbd  # 1.27
    #volumeHandle: 55b096c6-0b6b-4499-8f30-7893fb090a92 # 1.28
    #volumeHandle: 21d1446f-627f-434f-828b-4bfa917d24c9 # 1.29
