kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfs-turbo-static-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: sfs-turbo-static # This value is created in Step1.