apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-normal-pvc-default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-sc-default
