apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-sc-default
provisioner: evs.csi.huaweicloud.com
allowVolumeExpansion: true
parameters:
  type: SSD
reclaimPolicy: Delete
