kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-pvc-standard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: sfsturbo-sc-standard
