apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-snapshot-restore-pvc
spec:
  storageClassName: evs-snapshot-sc
  dataSource:
    name: evs-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
