apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-pvc-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: evs-sc-rwx
