apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-obs-static2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: obs.csi.huaweicloud.com
    volumeHandle: fs-test10086
