kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-obs-static2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-obs-static2
