apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-normal-pvc-paras
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: evs-sc-paras
