apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-parameter-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: evs-parameter-sc
