kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sfs-turbo-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: sfs-turbo-static # This value is created in Step1.