kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-performance-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: sfsturbo-performance-sc
