kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-pvc-performance
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: sfsturbo-sc-performance
