apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: evs-rwo-ds
spec:
  selector:
    matchLabels:
      app: evs-rwo
  template:
    metadata:
      labels:
        app: evs-rwo
    spec:
      containers:
        - image: nginx
          name: nginx1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/www/html
              name: shared-volume
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: evs-rwo-pvc
            readOnly: false
