apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-rwo-sc
provisioner: evs.csi.huaweicloud.com
allowVolumeExpansion: true
parameters:
  type: SSD
  multiattach: "true"
reclaimPolicy: Delete
