kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-default-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: sfsturbo-default-sc
