apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sfsturbo-default-sc
provisioner: sfsturbo.csi.huaweicloud.com
reclaimPolicy: Delete
parameters:
  shareType: STANDARD
  availability: eu-west-0a
