apiVersion: v1
kind: Pod
metadata:
  name: evs-pod-resize2
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/html
          name: csi-data-evs
  volumes:
    - name: csi-data-evs
      persistentVolumeClaim:
        claimName: evs-pvc-resize
        readOnly: false
