apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-pvc-resize
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: evs-sc-resize
