apiVersion: v1
kind: Pod
metadata:
  name: sfsturbo-allow-resize-pod
spec:
  containers:
    - image: nginx
      name: sfsturbo-nginx-scale-in
      command: [ "/bin/sh" ]
      args: [ "-c", "while true; do echo $(date -u) >> /mnt/sfsturbo/outfile; sleep 5; done" ]
      volumeMounts:
        - mountPath: /mnt/sfsturbo
          name: sfsturbo-data
  volumes:
    - name: sfsturbo-data
      persistentVolumeClaim:
        claimName: sfsturbo-allow-resize-pvc
