kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-allow-resize-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: sfsturbo-allow-resize-sc
