kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sfsturbo-pvc-reject-expand
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  storageClassName: sfsturbo-sc-reject-expand
