apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sfsturbo-sc-reject-expand
provisioner: sfsturbo.csi.huaweicloud.com
allowVolumeExpansion: false
reclaimPolicy: Delete
parameters:
  # shareType is required, should be 'STANDARD' or 'PERFORMANCE', defaults to 'STANDARD'
  shareType: STANDARD
