apiVersion: v1
kind: Pod
metadata:
  name: evs-rwx-pod
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx1
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/html
          name: shared-volume
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: evs-rwx-pvc
        readOnly: false
