apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: evs-rwx-sc
