apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-pvc-no-expend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-sc-no-expend
