apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-sc-no-expend
provisioner: evs.csi.huaweicloud.com
allowVolumeExpansion: false
parameters:
  type: SSD
reclaimPolicy: Delete
